### PR TITLE
Add contribution workflow guidelines

### PR DESCRIPTION
**Pull request by zolkis**
Signed-off-by: Zoltan Kis <zoltan.kis@intel.com>

### CODE REVIEW

**Comment by zolkis** [comment]
Will include a link in the README.md to [https://github.com/w3c/wotwg/blob/master/README.md#contributing](https://github.com/w3c/wotwg/blob/master/README.md#contributing) after [this](https://github.com/w3c/wotwg/pull/5) is merged.

**Comment by zolkis** [comment]
Rendered: https://github.com/zolkis/wotwg/blob/master/README.md

**Comment by mkovatsc** [comment]
Looks good to me. However, should this maybe rather go into CONTRIBUTING.md?

**Comment by mkovatsc** [comment]
Okay, let's keep it simple and merge to the readme. The other file seems to be a W3C standard. To get the benefit of GitHub showing the guidlines when opening pull requests, we would need to distribute the full CONTRIBUTING.md to all repos...

+1 for merging.

**Pull request merged**
